### ISSUE TITLE
Demo Docker Not work

### ISSUE THREAD

**Issue by peterson-umoke** [simolus3/asterisk.dart#2]
Your package arrived just in time. But having issuers with demo docker setup, see error 
```
Unable to find image 'ghcr.io/simolus3/asterisk_demo:latest' locally
docker: Error response from daemon: Head "https://ghcr.io/v2/simolus3/asterisk_demo/manifests/latest": unauthorized.
See 'docker run --help'.
```

**Comment by simolus3** [comment]
Apologies for the broken link, pulling `europe-docker.pkg.dev/simonbinder/public/asterisk_demo:latest`  should work and is public. I've updated the readme.
